[client]
showErrorDetails = false
toolbarMode = "viewer"

[server]
enableXsrfProtection = true        # Keamanan WAJIB
enableCORS = false                 # Restrict access
headless = true                    # Mode production

[browser]
gatherUsageStats = false           # Privacy user

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"