[client]
showErrorDetails = false
toolbarMode = "minimal"

[server]
enableXsrfProtection = true        # Keamanan WAJIB
enableCORS = false                 # Restrict access
headless = true                    # Mode production

[browser]
gatherUsageStats = false           # Privacy user

